name:                tic-tac-typed
version:             0.1.0.0
github:              "mstksg/tic-tac-typed"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/tic-tac-typed#readme>

ghc-options:
- -Wall
- -fno-max-relevant-binds

dependencies:
- base >= 4.7 && < 5
- mtl
- mwc-random
- primitive
- singletons
- transformers
- type-combinators

library:
  source-dirs: src
  other-modules:
  - Data.Type.Sel
  dependencies:
  - containers
  - dependent-map
  - dependent-sum
  - foldl
  - haskeline
  - type-combinators-singletons
  - vector

executables:
  tic-tac-typed-console:
    main:                console.hs
    source-dirs:         app
    dependencies:
    - tic-tac-typed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2

# tests:
#   tic-tac-typed-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - tic-tac-typed
